const state = { addon: null, blocks: [], activeBlock: null, workspace: null };
const $ = (selector) => document.querySelector(selector);
const ui = {
  launcherScreen: $("#launcherScreen"), projectScreen: $("#projectScreen"), blockEditorScreen: $("#blockEditorScreen"),
  newAddonButton: $("#newAddonButton"), newAddonModal: $("#newAddonModal"), newAddonForm: $("#newAddonForm"), addonNameInput: $("#addonNameInput"), addonDescriptionInput: $("#addonDescriptionInput"),
  projectNameLabel: $("#projectNameLabel"), projectDescriptionLabel: $("#projectDescriptionLabel"), emptyTree: $("#emptyTree"), projectTree: $("#projectTree"), moreButton: $("#moreButton"), moreMenu: $("#moreMenu"),
  createNewButton: $("#createNewButton"), createPanel: $("#createPanel"), closeCreatePanel: $("#closeCreatePanel"), createBlockButton: $("#createBlockButton"),
  newBlockModal: $("#newBlockModal"), newBlockForm: $("#newBlockForm"), blockNameInput: $("#blockNameInput"), blockIdInput: $("#blockIdInput"),
  heroTitle: $("#heroTitle"), heroText: $("#heroText"), canvasTitle: $("#canvasTitle"), welcomeMessage: $("#welcomeMessage"), addVisualBlockButton: $("#addVisualBlockButton"),
  backToLauncherButton: $("#backToLauncherButton"), backToProjectButton: $("#backToProjectButton"), blockNameLabel: $("#blockNameLabel"), blockIdLabel: $("#blockIdLabel"),
  activeFileName: $("#activeFileName"), filePreview: $("#filePreview"), blockPalette: $("#blockPalette"), openBlockPaletteButton: $("#openBlockPaletteButton"), closeBlockPalette: $("#closeBlockPalette")
};
function showScreen(name){ ui.launcherScreen.classList.toggle("hidden", name!=="launcher"); ui.projectScreen.classList.toggle("hidden", name!=="project"); ui.blockEditorScreen.classList.toggle("hidden", name!=="editor"); if(name==="editor") setTimeout(()=>state.workspace?.resize?.(), 50); }
function openModal(modal){ modal.classList.remove("hidden"); } function closeModals(){ document.querySelectorAll(".modal").forEach(m=>m.classList.add("hidden")); }
function slugify(value){ return value.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"") || "mi_bloque"; }
function createAddon(name, description){ state.addon={name:name.trim(),description:description.trim()}; state.blocks=[]; state.activeBlock=null; renderApp(); showScreen("project"); }
function createBasicBlock(name, identifier){ const slug=slugify(name); const block={type:"block",name:name.trim(),identifier:identifier.trim(),slug,behaviorPath:`behavior_packs/blocks/${slug}.json`,resourcePath:`resource_packs/blocks/${slug}.json`,texturePath:`resource_packs/textures/blocks/${slug}.png`}; state.blocks.push(block); state.activeBlock=block; renderApp(); showBlockEditor(block); }
function renderApp(){ const hasAddon=Boolean(state.addon); ui.projectNameLabel.textContent=hasAddon?state.addon.name:"Sin complemento"; ui.projectDescriptionLabel.textContent=hasAddon?(state.addon.description||"Sin descripción. Alpha sin manifest todavía."):"Crea un complemento para comenzar."; ui.heroTitle.textContent=hasAddon?`Complemento: ${state.addon.name}`:"Complemento abierto"; ui.heroText.textContent="Aquí se organiza tu complemento. Las carpetas rojas son comportamiento y las azules son recursos."; ui.canvasTitle.textContent=hasAddon?"Panel del complemento":"Nada creado todavía"; ui.moreButton.disabled=!hasAddon; if(!hasAddon||state.blocks.length===0){ ui.emptyTree.classList.remove("hidden"); ui.projectTree.classList.add("hidden"); ui.projectTree.innerHTML=""; ui.addVisualBlockButton.disabled=true; return;} ui.emptyTree.classList.add("hidden"); ui.projectTree.classList.remove("hidden"); ui.projectTree.innerHTML=buildTreeHtml(); ui.addVisualBlockButton.disabled=false; document.querySelectorAll(".file-item.clickable").forEach(item=>item.addEventListener("click",()=>{ const block=state.blocks.find(b=>b.identifier===item.dataset.blockId); if(block) showBlockEditor(block); })); }
function buildTreeHtml(){ const behaviorFiles=state.blocks.map(block=>`<div class="file-item clickable visual" data-block-id="${block.identifier}">▣ ${block.name} · editor visual</div><div class="file-item">${block.behaviorPath}</div>`).join(""); const resourceFiles=state.blocks.map(block=>`<div class="file-item">${block.resourcePath}</div><div class="file-item">${block.texturePath}</div>`).join(""); return `<div class="folder red"><div class="folder-title">■ Behavior Pack</div>${behaviorFiles}</div><div class="folder blue"><div class="folder-title">■ Resource Pack</div>${resourceFiles}</div>`; }
function buildBehaviorPreview(block){ return JSON.stringify({format_version:"1.20.80","minecraft:block":{description:{identifier:block.identifier},components:{"minecraft:destructible_by_mining":{"seconds_to_destroy":5},"minecraft:friction":0.6}}},null,2); }
function showBlockEditor(block){ state.activeBlock=block; showScreen("editor"); ui.blockNameLabel.textContent=block.name; ui.blockIdLabel.textContent=block.identifier; ui.activeFileName.textContent=block.behaviorPath; ui.filePreview.textContent=buildBehaviorPreview(block); initializeBlocklyOnce(); }
function initializeBlocklyOnce(){ if(state.workspace) return; Blockly.Blocks.jumbo_block_health={init(){this.appendDummyInput().appendField("resistencia del bloque").appendField(new Blockly.FieldNumber(5,1,100),"RESISTANCE");this.setColour(285);this.setTooltip("Bloque visual alpha para comportamiento básico.");}}; Blockly.Blocks.jumbo_block_resistance={init(){this.appendDummyInput().appendField("destruir con herramienta").appendField(new Blockly.FieldDropdown([["pico","pickaxe"],["mano","hand"]]),"TOOL");this.setColour(260);this.setTooltip("Define una herramienta sugerida.");}}; state.workspace=Blockly.inject("blocklyDiv",{toolbox:document.getElementById("toolbox"),trashcan:true,scrollbars:true,zoom:{controls:true,wheel:true,startScale:.85,maxScale:1.4,minScale:.5,scaleSpeed:1.1}}); }
function spawnBlocklyBlock(type){ initializeBlocklyOnce(); const block=state.workspace.newBlock(type); block.initSvg(); block.render(); block.moveBy(40+Math.random()*80,40+Math.random()*80); ui.blockPalette.classList.add("hidden"); }
ui.newAddonButton.addEventListener("click",()=>openModal(ui.newAddonModal)); ui.newAddonForm.addEventListener("submit",e=>{e.preventDefault();createAddon(ui.addonNameInput.value,ui.addonDescriptionInput.value);closeModals();ui.newAddonForm.reset();}); ui.backToLauncherButton.addEventListener("click",()=>showScreen("launcher")); ui.backToProjectButton.addEventListener("click",()=>{renderApp();showScreen("project");}); ui.moreButton.addEventListener("click",()=>{if(state.addon)ui.moreMenu.classList.toggle("hidden")}); ui.createNewButton.addEventListener("click",()=>{ui.moreMenu.classList.add("hidden");ui.createPanel.classList.remove("hidden")}); ui.closeCreatePanel.addEventListener("click",()=>ui.createPanel.classList.add("hidden")); ui.createBlockButton.addEventListener("click",()=>{ui.createPanel.classList.add("hidden");ui.blockIdInput.value=state.addon?`jumbo:${slugify(state.addon.name)}_block`:"jumbo:mi_bloque";openModal(ui.newBlockModal);}); ui.newBlockForm.addEventListener("submit",e=>{e.preventDefault();createBasicBlock(ui.blockNameInput.value,ui.blockIdInput.value);closeModals();ui.newBlockForm.reset();}); ui.addVisualBlockButton.addEventListener("click",()=>{const block=state.activeBlock||state.blocks[0]; if(block)showBlockEditor(block);}); ui.openBlockPaletteButton.addEventListener("click",()=>ui.blockPalette.classList.remove("hidden")); ui.closeBlockPalette.addEventListener("click",()=>ui.blockPalette.classList.add("hidden")); document.querySelectorAll(".palette-option").forEach(button=>button.addEventListener("click",()=>spawnBlocklyBlock(button.dataset.spawnBlock))); document.querySelectorAll("[data-close-modal]").forEach(button=>button.addEventListener("click",closeModals)); renderApp(); showScreen("launcher");